accountapp/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name = 'login'),
    path('logout/', LogoutView.as_view(), name = 'logout'),

    path('create/', AccountCreateView.as_view(), name = 'create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name = 'detail'), # detail.html에는 pk가 필요하다!
    path('update/<int:pk>', AccountUpdateView.as_view(), name = 'update'), # update.html에는 pk가 필요하다!
    path('delete/<int:pk>', AccountDeleteView.as_view(), name = 'delete'), # detail.html에는 pk가 필요하다!
]

pagesapp/urls.py
# pagesapp/urls.py
from django.urls import path
from .views import notice_view, partnership_view, about_view

app_name = 'pagesapp'

urlpatterns = [
    path('notice/', notice_view, name='notice'),
    path('partnership/', partnership_view, name='partnership'),
    path('about/', about_view, name='about'),
]

pragmatic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from articleapp.views import ArticleListView

# superuser: admin / whdrbs9914


urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscriptions/', include('subscriptionapp.urls')),
    path('pages/', include('pagesapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path
from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'


urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

from projectapp.models import Project


# Create your models here.


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='article', null=True)

    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_created=True, null=True)

accountapp/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordChangeView
from django.urls.base import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountapp.decorators import account_ownership_required
from articleapp.models import Article


# Create your views here.
class AccountCreateView(CreateView): #계정 생성 클래스. class based view
    model = User
    form_class = UserCreationForm  # 계정
    success_url = reverse_lazy('accountapp:login') # 계정 생성 성공 시 다시 연결될 경로
    template_name = 'accountapp/create.html'


@method_decorator(login_required, name='dispatch') # 다른 유저의 정보를 보는 것은 로그인이 필요하다고 판단
class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user' # 127.0.0.1:8000/accounts/detail/5에서 5가 바로 target_user
    template_name = 'accountapp/detail.html'

    paginate_by = 25 # 게시물 페이지네이션 개수

    def get_context_data(self, **kwargs):
        object_list = Article.objects.filter(writer=self.get_object()) # 현재 페이지에서 조회 중인 유저의 게시물 가져오기

        return super(AccountDetailView, self).get_context_data(object_list=object_list, **kwargs)


@method_decorator(login_required, name='dispatch')
@method_decorator(account_ownership_required, name='dispatch')
class AccountUpdateView(PasswordChangeView):
    model = User
    form_class = PasswordChangeForm
    template_name = 'accountapp/update.html'
    success_url = reverse_lazy('accountapp:login')

    def form_valid(self, form):
        response = super().form_valid(form)
        logout(self.request)  # 비밀번호 변경 후 로그아웃

        return response


@method_decorator(login_required, name='dispatch')
@method_decorator(account_ownership_required, name='dispatch')
class AccountDeleteView(DeleteView):
    model = User
    template_name = 'accountapp/delete.html'
    success_url = reverse_lazy('accountapp:login')

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
  <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
      <h4>SignUp</h4>
    </div>
    <form action="{% url 'accountapp:create' %}" method="post">
      {% csrf_token %}

      {% bootstrap_form  form %}
      <input type="submit" class="btn btn-dark rounded-pill col-4 mt-4">
    </form>
  </div>
{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% block content %}
  <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
      <h6>
        해당 계정을 삭제하면 복구할 수 없습니다.<br><br>
        정말로 삭제하시겠습니까?
      </h6>
    </div>
    <form action="{% url 'accountapp:delete' pk=user.pk %}" method="post">
      {% csrf_token %}
      <input type="submit" class="btn btn-danger rounded-pill col-2 mt-4" value="삭제">
    </form>
  </div>
{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}
{% load tz %} <!--  time zone  -->

{% block content %}

    <div>
        <div style="text-align: center; max-width: 500px; margin: 4rem auto">

            {% if target_user.profile %}
                <img src="{{ target_user.profile.image.url }}" alt=""
                     style="height: 10rem; width: 10rem; border-radius: 10rem; margin-bottom: 2rem; object-fit: cover;">


                <h2>
                    {{ target_user.profile.nickname }}

                    {% if target_user == user %}
                        <a class="material-icons"
                           style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem;
                           text-decoration: none;"
                           href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
                            <h5 style="margin: 0;">
                                edit
                            </h5>
                        </a>

                    {% endif %}
                </h2>

                <h5 style="margin-top: 2rem; margin-bottom: 1.5rem;">
                    {{ target_user.profile.message }}
                </h5>
            {% else %}
                {% if target_user == user %}
                    <a href="{% url 'profileapp:create' %}">
                        <h2 style="margin-bottom: 3rem;">
                            CreateProfile
                        </h2>
                    </a>
                {% else %}
                    <h2>
                        프로필이 없습니다!
                    </h2>
                {% endif %}
            {% endif %}

            {% if target_user == user %}
            <a class="material-icons"
                           style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem; text-decoration: none;
                                margin-right: 5px;"
                    href="{% url 'accountapp:update' pk=user.pk %}">
                vpn_key
            </a>
            <a class="material-icons"
                           style="box-shadow: 0 0 4px #fcc; border-radius: 10rem; padding: .4rem; text-decoration: none;";
                    href="{% url 'accountapp:delete' pk=user.pk %}">
                delete_forever
            </a>
            {% endif %}

        </div>

        <div>
            {% include 'snippets/list_fragment.html' with article_list=object_list %} <!--  내가 생성한 article 출력  -->
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    {% if user.is_authenticated %}
        <script>
            window.location.href = "{% url 'home' %}";
        </script>
    {% else %}
        <div style="text-align: center; max-width: 500px; margin: 4rem auto">
            <div>
                <h4>Login</h4>
            </div>
            <div>
                <form action="" method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}

                    {% if request.GET.next == "/accounts/create/" %}
                        <input type="hidden" name="next" value="">
                    {% elif request.GET.next %}
                        <input type="hidden" name="next" value="{{ request.GET.next }}">
                    {% endif %}

                    <input type="submit" class="btn btn-dark rounded-pill col-4 mt-4">
                </form>
            </div>
        </div>
    {% endif %}

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
  <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
      <h4>비밀번호 변경</h4>
    </div>
    <form action="{% url 'accountapp:update' pk=user.pk %}" method="post">
      {% csrf_token %}

      {% bootstrap_form  form %}
      <input type="submit" class="btn btn-dark rounded-pill col-2 mt-4" value="변경">
    </form>
  </div>
{% endblock %}