pagesapp/urls.py
# pagesapp/urls.py
from django.urls import path
from .views import notice_view, partnership_view, about_view

app_name = 'pagesapp'

urlpatterns = [
    path('notice/', notice_view, name='notice'),
    path('partnership/', partnership_view, name='partnership'),
    path('about/', about_view, name='about'),
]

pragmatic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from articleapp.views import ArticleListView

# superuser: admin / whdrbs9914


urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscriptions/', include('subscriptionapp.urls')),
    path('pages/', include('pagesapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView, ProjectDeleteView, ProjectUpdateView

app_name = 'projectapp'

urlpatterns = [
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', ProjectDeleteView.as_view(), name='delete'),
    path('update/<int:pk>/', ProjectUpdateView.as_view(), name='update'),
    path('list/', ProjectListView.as_view(), name='list'),
]

subscriptionapp/urls.py
from django.urls import path

from subscriptionapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscriptionapp'

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

from projectapp.models import Project


# Create your models here.


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='article', null=True)

    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_created=True, null=True)

projectapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Project(models.Model):
    name = models.CharField(max_length=20, null=False)
    description = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='project/', null=False)

    created_at = models.DateTimeField(auto_now_add=True)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='projects')  # 추가돼 있어야 함

    def __str__(self):
        return f"{self.pk} : {self.name}"

projectapp/forms.py
from django.forms import ModelForm

from projectapp.models import Project


class ProjectCreationForm(ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'image', 'description']

projectapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

# Create your views here.
from django.urls import reverse
from django.urls.base import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, ListView
from django.views.generic.edit import DeleteView, UpdateView
from django.views.generic.list import MultipleObjectMixin

from articleapp.models import Article
from projectapp.forms import ProjectCreationForm
from projectapp.models import Project
from subscriptionapp.models import Subscription


@method_decorator(login_required,'dispatch')
class ProjectCreateView(CreateView):
    model = Project
    form_class = ProjectCreationForm
    template_name = 'projectapp/create.html'

    def form_valid(self, form):
        form.instance.writer = self.request.user  # 작성자 설정
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('projectapp:detail', kwargs={'pk': self.object.pk})


class ProjectDetailView(DetailView, MultipleObjectMixin):
    model = Project
    context_object_name = 'target_project'
    template_name = 'projectapp/detail.html'

    paginate_by = 10

    def get_context_data(self, **kwargs):
        project = self.object
        user = self.request.user

        if user.is_authenticated:
            subscription = Subscription.objects.filter(user=user, project=project)
        else:
            subscription = None

        object_list = Article.objects.filter(project=self.get_object())

        return super(ProjectDetailView, self).get_context_data(object_list=object_list, subscription=subscription, **kwargs)


class ProjectListView(ListView):
    model = Project
    context_object_name = 'project_list'
    template_name = 'projectapp/list.html'
    paginate_by = 10


class ProjectUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Project
    template_name = 'projectapp/update.html'
    fields = ['name', 'description', 'image']
    context_object_name = 'target_project'

    def form_valid(self, form):
        form.instance.writer = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('projectapp:detail', kwargs={'pk': self.object.pk})

    def test_func(self):
        return self.get_object().writer == self.request.user


class ProjectDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Project
    context_object_name = 'target_project'
    template_name = 'projectapp/delete.html'
    success_url = reverse_lazy('home')  # 삭제 후 이동할 페이지

    def test_func(self):
        return self.request.user == self.get_object().writer

projectapp/templates/projectapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
      <h4>프로젝트 생성</h4>
    </div>
    <form action="{% url 'projectapp:create' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}

      {% bootstrap_form  form %}
      <input type="submit" class="btn btn-dark rounded-pill col-2 mt-4" value="생성">
    </form>
  </div>

{% endblock %}

projectapp/templates/projectapp/delete.html
{% extends 'base.html' %}

{% block content %}
  <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
      <h4 style="margin-bottom: 2rem">Delete Project : {{ target_project.name }}</h4>
      <h6>
        해당 프로젝트를 삭제하면 복구할 수 없습니다.<br><br>
        정말로 삭제하시겠습니까?
      </h6>
    </div>
    <form method="post">
      {% csrf_token %}
      <input type="submit" class="btn btn-danger rounded-pill col-2 mt-4" value="삭제">
    </form>
  </div>
{% endblock %}

projectapp/templates/projectapp/detail.html
{% extends 'base.html' %}

{% block content %}

    <div>
        <div style="text-align: center; max-width: 500px; margin: 3rem auto 1.5rem auto">

            <img src="{{ target_project.image.url }}" alt=""
                     style="height: 10rem; width: 10rem; border-radius: 10rem; margin-bottom: 2rem; object-fit: cover;">

            <h2>
                <strong>
                    {{ target_project.name }}
                </strong>
            </h2>

            <h6 style="margin-top: 1rem;">
                <p>{{ target_project.description|linebreaksbr }}</p>
            </h6>

        </div>

        <div class="text-center mb-5">
            {% if user.is_authenticated %}
                {% if not subscription %}
                    <a href="{% url 'subscriptionapp:subscribe' %}?project_pk={{ target_project.pk }}"
                        class="btn btn-primary rounded-pill px-3">
                        구독
                    </a>
                {% else %}
                    <a href="{% url 'subscriptionapp:subscribe' %}?project_pk={{ target_project.pk }}"
                        class="btn btn-dark rounded-pill px-3">
                        구독 취소
                    </a>
                {% endif %}
            {% endif %}
        </div>

        <div>
            {% include 'snippets/list_fragment.html' with article_list=object_list %}
        </div>

        {% if user == target_project.writer %}
            <div style="text-align: center;">
                <a href="{% url 'projectapp:update' pk=target_project.pk %}"
                   class="btn btn-secondary rounded-pill col-1 mt-5 mb-3"
                   style="margin-right: 1rem;">
                    업데이트
                </a>

                <a href="{% url 'projectapp:delete' pk=target_project.pk %}"
                     class="btn btn-dark rounded-pill col-1 mt-5 mb-3">
                    프로젝트 삭제
                </a>
            </div>

        {% endif %}
    </div>

{% endblock %}

projectapp/templates/projectapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <style>
    .container {
      padding: 0;
      margin: 0, auto;
    }

    .container div {
      display: flex;
      justify-content: center;
      align-items: center;
      border-radius: 1rem;
    }

    .container img {
      width: 7rem;
      height: 7rem;
      object-fit: cover;
      border-radius: 1rem;
    }
  </style>


  {% if project_list %}
    <div class="container">
      {% for pjt in project_list %}
        <a href="{% url 'projectapp:detail' pk=pjt.pk %}">
          {% include 'snippets/card_project.html' with project=pjt %}
        </a>
      {% endfor %}
    </div>

    <script src="{% static 'js/magicgrid.js' %}"></script>
  {% else %}
    <div class="text-center">
      <br><h5>아직 프로젝트가 없습니다!</h5><br>
    </div>
  {% endif %}

  {% include 'snippets/pagination.html' with page_obj=page_obj %}

  <div style="text-align: center">
    <a href="{% url 'projectapp:create' %}" class="btn btn-dark rounded-pill col-1 mt-3 mb-3 px-3">
      프로젝트 생성
    </a>
  </div>

{% endblock %}

projectapp/templates/projectapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
  <div style="max-width: 500px; margin: 4rem auto; text-align: center;">
    <h4>프로젝트 업데이트</h4>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button type="submit" class="btn btn-dark rounded-pill col-3 mt-4">업데이트</button>
    </form>
  </div>
{% endblock %}