accountapp/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name = 'login'),
    path('logout/', LogoutView.as_view(), name = 'logout'),

    path('create/', AccountCreateView.as_view(), name = 'create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name = 'detail'), # detail.html에는 pk가 필요하다!
    path('update/<int:pk>', AccountUpdateView.as_view(), name = 'update'), # update.html에는 pk가 필요하다!
    path('delete/<int:pk>', AccountDeleteView.as_view(), name = 'delete'), # detail.html에는 pk가 필요하다!
]

articleapp/urls.py
from django.urls import path

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = "articleapp"

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

pagesapp/urls.py
# pagesapp/urls.py
from django.urls import path
from .views import notice_view, partnership_view, about_view

app_name = 'pagesapp'

urlpatterns = [
    path('notice/', notice_view, name='notice'),
    path('partnership/', partnership_view, name='partnership'),
    path('about/', about_view, name='about'),
]

pragmatic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from articleapp.views import ArticleListView

# superuser: admin / whdrbs9914


urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscriptions/', include('subscriptionapp.urls')),
    path('pages/', include('pagesapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView, ProjectDeleteView, ProjectUpdateView

app_name = 'projectapp'

urlpatterns = [
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', ProjectDeleteView.as_view(), name='delete'),
    path('update/<int:pk>/', ProjectUpdateView.as_view(), name='update'),
    path('list/', ProjectListView.as_view(), name='list'),
]

subscriptionapp/urls.py
from django.urls import path

from subscriptionapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscriptionapp'

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

templates/base.html
<!doctype html>
<html lang="ko">

{% include 'head.html' %}

<body>

    {% include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}

    <hr>

    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
<div class="pragmatic_footer">

    <div class="pragmatic_footer_button">
        <a href="{% url 'pagesapp:notice' %}" style="text-decoration: none;"><span>공지사항</span></a> |
        <a href="{% url 'pagesapp:partnership' %}" style="text-decoration: none;"><span>제휴문의</span></a> |
        <a href="{% url 'pagesapp:about' %}" style="text-decoration: none;"><span>서비스 소개</span></a>
    </div>

    <div style="margin-top: 1rem;">
        <a href="{% url 'home' %}" style="text-decoration: none;">
            <h6 class="pragmatic_logo">AttackOnTitan Archive</h6>
        </a>
    </div>

</div>

templates/head.html
{% load static %}


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>AOT Archive</title>

    <!--  bootstrap link  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!--  google fonts link Manufacturing Consent AOT?  -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anton&family=Manufacturing+Consent&display=swap" rel="stylesheet">

    <!--  google fonts link Staatliches  -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Staatliches&display=swap" rel="stylesheet">

    <!--  google fonts link Lobster -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">


    <!--  DEFAULT CSS LINK  -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <!--  GOOGLE MATERIAL ICONS  -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">
</head>

templates/header.html
<div class="pragmatic_header">

    <div>
        <a href="{% url 'home' %}" style="text-decoration: none;">
            <h1 class="pragmatic_logo">AttackOnTitan Archive</h1>
        </a>
    </div>

    <div>
        <a href="{% url 'articleapp:list' %}" style="text-decoration: none; color: black;">
            <span style="margin-right: 10px;">Articles</span>
        </a>

        <a href="{% url 'projectapp:list' %}" style="text-decoration: none; color: black;">
            <span style="margin-right: 10px;">Projects</span>
        </a>

        {% if not user.is_authenticated %}
            <a href="{% url 'accountapp:login' %}?next={{ request.path }} " style="text-decoration: none; color: black;">
                <span style="margin-right: 10px;">login</span>
            </a>

            <a href="{% url 'accountapp:create' %}" style="text-decoration: none; color: black;">
                <span style="margin-right: 10px;">SignUp</span>
            </a>
        {% else %}
            <a href="{% url 'subscriptionapp:list' %}" style="text-decoration: none; color: black;">
                <span style="margin-right: 10px;">Subscription</span>
            </a>

            <a href="{% url 'accountapp:detail' pk=user.pk %}" style="text-decoration: none; color: black; margin-right: 10px;">
                <span>MyPage</span>
            </a>

            <form action="{% url 'accountapp:logout' %}" method="post" style="display: inline;">
                {% csrf_token %}
                <button type="submit" style="background: none; border: none; padding: 0; margin: 0; color: inherit; font: inherit; cursor: pointer;">
                    <span>Logout</span>
                </button>
            </form>
        {% endif %}
    </div>
</div>